version: '3.8'

services:
  client-react-nginx:
    container_name: client-react-nginx
    image: bosukeme/client-react-nginx:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    init: true
    networks:
      - frontend
    ports:
      - 80:8080

  api-node:
    container_name: api-node
    image: bosukeme/api-node:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    read_only: true
    init: true
    depends_on:
      - db
    env_file:
      - .env.local
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000


  api-flask:
    container_name: api-flask
    image: bosukeme/api-flask:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    read_only: true
    init: true
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
      - frontend
    ports:
      - 5000:5000

  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  pgdata:

networks:
  frontend:
  backend:
