# Overlay configuration to run tests
version: "3.9"
services:
  api-node:
    image: directive-api-node
    command: 
      - "npm"
      - "run"
      - "test"
  
  api-flask:
    image: directive-api-flask
    command: 
      - "python3"
      - "test/test_example.py"



# docker-compose -f docker-compose-test.yaml run api-flask
