name: containers-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the docker images
        run: docker-compose build

      - name: Tag Docker images
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker tag client-react-nginx bosukeme/client-react-nginx:${IMAGE_TAG}
          docker tag api-node bosukeme/api-node:${IMAGE_TAG}
          docker tag api-flask bosukeme/api-flask:${IMAGE_TAG}

      
      - name: Push Docker images
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker push bosukeme/client-react-nginx:${IMAGE_TAG}
          docker push bosukeme/api-node:${IMAGE_TAG}
          docker push bosukeme/api-flask:${IMAGE_TAG}