name: containers-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build the docker images
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/bosukeme/client-react-nginx/tags/?page_size=1 | jq -r '.results[0].name')
          echo "Latest tag is: ${LATEST_TAG}"
          export IMAGE_TAG=${LATEST_TAG}
          docker compose build

      - name: List Docker images
        run:
          docker images

      - name: Tag Docker images
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/bosukeme/client-react-nginx/tags/?page_size=1 | jq -r '.results[0].name')
          NEW_TAG=$((LATEST_TAG + 1)) 
          echo "Re-fetched Latest tag is: ${LATEST_TAG}"
          echo "Re-fetched Latest tag is: ${NEW_TAG}"
          docker tag bosukeme/client-react-nginx:${LATEST_TAG} bosukeme/client-react-nginx:${NEW_TAG}
          docker tag bosukeme/api-node:${LATEST_TAG} bosukeme/api-node:${NEW_TAG}
          docker tag bosukeme/api-flask:${LATEST_TAG} bosukeme/api-flask:${NEW_TAG}

      
      - name: Push Docker images
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/bosukeme/client-react-nginx/tags/?page_size=1 | jq -r '.results[0].name')
          NEW_TAG=$((LATEST_TAG + 1))
          docker push bosukeme/client-react-nginx:${NEW_TAG}
          docker push bosukeme/api-node:${NEW_TAG}
          docker push bosukeme/api-flask:${NEW_TAG}