name: containers-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
      
      - name: Build the docker images
        run: |
          docker compose build --build-arg IMAGE_TAG=${{ env.IMAGE_TAG }}

      - name: List Docker images
        run:
          docker images

      - name: Tag Docker images
        run: |
          docker tag bosukeme/client-react-nginx bosukeme/client-react-nginx:${{ env.IMAGE_TAG }}
          docker tag bosukeme/api-node bosukeme/api-node:${{ env.IMAGE_TAG }}
          docker tag bosukeme/api-flask bosukeme/api-flask:${{ env.IMAGE_TAG }}

      
      - name: Push Docker images
        run: |
          docker push bosukeme/client-react-nginx:${{ env.IMAGE_TAG }}
          docker push bosukeme/api-node:${{ env.IMAGE_TAG }}
          docker push bosukeme/api-flask:${{ env.IMAGE_TAG }}